package ltc

/**
 *
 * @export
 * @interface LtcUTXO
 */
type LtcUTXO struct {

	/**
	 * Version of the UTXO.
	 * @type {number}
	 * @memberof LtcUTXO
	 */
	Version uint32
	/**
	 *
	 * @type {number}
	 * @memberof LtcUTXO
	 */
	Height uint32
	/**
	 * Amount of UTXO in satoshis.
	 * @type {string}
	 * @memberof LtcUTXO
	 */
	Value string
	/**
	 * Data generated by a spender which is almost always used as variables to satisfy a pubkey script.
	 * @type {string}
	 * @memberof LtcUTXO
	 */
	Script string
	/**
	 * Address of the owner of the UTXO.
	 * @type {string}
	 * @memberof LtcUTXO
	 */
	Address string
	/**
	 * Coinbase transaction - miner fee.
	 * @type {boolean}
	 * @memberof LtcUTXO
	 */
	Coinbase bool
	/**
	 * Transaction hash.
	 * @type {string}
	 * @memberof LtcUTXO
	 */
	Hash string
	/**
	 * Transaction index of the output.
	 * @type {number}
	 * @memberof LtcUTXO
	 */
	Index uint32
}
