package btc

type UTXO struct {

	/**
	 * Version of the UTXO.
	 * @type {number}
	 * @memberof BtcUTXO
	 */
	Version int
	/**
	 *
	 * @type {number}
	 * @memberof BtcUTXO
	 */
	Height uint64
	/**
	 * Amount of UTXO in satoshis.
	 * @type {number}
	 * @memberof BtcUTXO
	 */
	Value uint64
	/**
	 * Data generated by a spender which is almost always used as variables to satisfy a pubkey script.
	 * @type {string}
	 * @memberof BtcUTXO
	 */
	Script string
	/**
	 * Address of the owner of the UTXO.
	 * @type {string}
	 * @memberof BtcUTXO
	 */
	Address string
	/**
	 * Coinbase transaction - miner fee.
	 * @type {boolean}
	 * @memberof BtcUTXO
	 */
	Coinbase bool
	/**
	 * Transaction hash.
	 * @type {string}
	 * @memberof BtcUTXO
	 */
	Hash string
	/**
	 * Transaction index of the output.
	 * @type {number}
	 * @memberof BtcUTXO
	 */
	Index uint32
}
